name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/Container/**'

defaults:
  run:
    working-directory: Frontend/Container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az storage blob upload-batch --debug --account-name uistorageabsar --account-key zhMCK0jubTC16KjhL3UeJ77TXiFKeueWb+fZdEojXrc1NjAFmve2nZgoU6/xZVVNQMfHQA3k+aqEe4qvbgp1Hw==  --auth-mode key -d web  -s .       

